export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Toaster } from "react-hot-toast"
import "../../styles/globals.css"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center h-screen w-full">
        <Toaster position="bottom-center" />
        {children}
      </body>
    </html>
  )
}
