export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "../../styles/globals.css"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center h-screen w-full">{children}</body>
    </html>
  )
}
