networks:
  iuxit-net:
    external: true

services:

  app:
    env_file:
      - .envs/app.env
    ports:
      - ${APP_HTTP_PUBLISH_PORT}:${APP_HTTP_PUBLISH_PORT}

    # Comment out volumes for "prod" mode
    volumes:
      - ${DOCKER_VOLUME_CODES_ROOT_DIR}:/usr/src
    networks:
      iuxit-net:
        aliases:
          - iuxit-charity-app
