import LeftSidebar from "@/components/dashboard-components/sidebar"
import "../../styles/globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="grid xl:grid-cols-5 lg:grid-cols-2 gap-6">
          <div className="col-span-1">
            <LeftSidebar />
          </div>
          <div className="xl:col-span-4 col-span-1 p-5 ps-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
